### ISSUE TITLE
Warning cleaning and linting

### ISSUE THREAD

**Issue by jmcarcell** [DUNE-DAQ/dqm#21]
There are a few warnings when compiling and some cleaning of obsolete parts would be good

**Comment by jcfreeman2** [comment]
Couple of other guideline issues I've observed while linting, most of them minor. Some of these deviations may have reasonable explanations, but as I'm not too familiar with this code I want to make sure this is the case:
* `cout` and `cerr` are used in place of the standard DUNE DAQ logging facilities (https://dune-daq-sw.readthedocs.io/en/latest/packages/logging/)
* Memory management is performed using raw owning pointers rather than smart pointers (`DQMProcessor.cpp`). The `TODO` comment which points this out is missing a name, date and email address, but this is a less serious deviation and does more harm than good regardless!
* The purpose of `daq_add_library` with no arguments in `CMakeLists.txt` would be to create a library other packages which call `find_package(dqm)` can link into their code to make the `Types.hpp` header accessible - this is what was intended, right?

The full style guide is located at https://dune-daq-sw.readthedocs.io/en/latest/packages/styleguide/

**Comment by jmcarcell** [comment]
Not relevant anymore
